CREATE TABLE batch
(id INTEGER NOT NULL,
name VARCHAR(25) NOT NULL,
start_date TIMESTAMP NOT NULL,
end_date TIMESTAMP NOT NULL,
trainer_id INTEGER,
calendar_curriculum_id INTEGER,
PRIMARY KEY (id));

CREATE SEQUENCE batch_seq START WITH 5;